version: "3.4"

services:
  php:
    build:
      context: .
      target: app_php-production
    restart: unless-stopped
#    volumes:
#      - ./php/logs/:/var/log/
    networks:
      - webapp

  nginx:
    build:
      context: .
      target: app_nginx
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
    depends_on:
      - php
    environment:
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME:-localhost}
    volumes:
      - ./nginx/var/cache/nginx:/var/cache/nginx
      - ./nginx/var/cache/nginx-pid:/var/run
      - ./nginx/var/log:/var/log/nginx/
      - ./docker/nginx/templates:/etc/nginx/templates
    networks:
      - webapp

networks:
  webapp:
    driver: bridge